<?php
    session_start();
    if(!isset($_SESSION['USER']) && !isset($_SESSION['ROLE_ID'])){
        header("location:../main/login.php");
    } else if($_SESSION['ROLE_ID'] != 1){
        header("location: ../main/not-found.php");
    }
    include_once '../partials/connectionString.php';
    $date_generated = mysqli_real_escape_string($conn, $_GET['date']);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reports</title>
    <?php require '../partials/imports.php' ?>
</head>
<body>
    <div class="report-print">
        <div class="print-page">
            <p class="shop-name"><i class='bx bxs-shopping-bag-alt' ></i>Shoe<span>pee</span></p>
            <p class="receipt-desc"><?php echo date_format(date_create($date_generated), "F d, Y") ?></p>
            <p class="receipt-desc">Sales Report</p>
        </div>

        <div class="report-table">
            <table>
                <thead>
                    <tr>
                        <td>Product</td>
                        <td>Price</td>
                        <td>Quantity</td>
                        <td>Amount Received</td>
                    </tr>
                </thead>
                <tbody>
                <?php
                    $sql = "SELECT p.product_name, p.price, o.amount, oi.quantity  FROM order_items oi INNER JOIN orders o ON oi.order_id=o.id INNER JOIN products p ON oi.product_id=p.id WHERE o.order_date='{$date_generated}'";
                    $query = mysqli_query($conn, $sql);
                    $total_sales = 0;
                    while($row = mysqli_fetch_assoc($query)){
                        $amount = $row['price'] * $row['quantity'];
                        $total_sales = $total_sales + $amount;
                        echo '<tr>
                                <td style="text-transform: capitalize">'.$row['product_name'].'</td>
                                <td>₱ '.$row['price'].'</td>
                                <td>'.$row['quantity'].'</td>
                                <td>₱ '.$amount.'</td>
                            </tr>';
                    }
                    echo '<tr>
                            <td style="font-size: 0.8rem">Generated by Shoepee Sales Management</td>
                            <td></td>
                            <td></td>
                            <td>Total Sales Amount <br> <b>₱ '.$total_sales.'</b></td>
                        </tr>';
                ?>
                </tbody>
            </table>
        </div>
    </div>

    <script src="../js/print.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>

</body>
</html>