<?php
    include_once '../partials/connectionString.php';
    $start_date = mysqli_real_escape_string($conn, $_POST['start_date']);
    $end_date = mysqli_real_escape_string($conn, $_POST['end_date']);
    if(!empty($start_date) && !empty($end_date)){
        $sql = "SELECT p.product_name, p.price, o.amount, oi.quantity  FROM order_items oi INNER JOIN orders o ON oi.order_id=o.id INNER JOIN products p ON oi.product_id=p.id WHERE o.order_date BETWEEN '{$start_date}' AND '{$end_date}'";
        $query = mysqli_query($conn, $sql);
        $output = '<div class="report-header">
                    <p class="shop-name"><i class="bx bxs-shopping-bag-alt"></i>Shoe<span>pee</span></p>
                    <p class="receipt-desc">'.date_format(date_create($start_date), "F d, Y").' '.date_format(date_create($end_date), "F d, Y").'</p>
                    <p class="receipt-desc">Sales Report</p>
                    <button class="report-close-btn"><i class="bx bx-x"></i></button>
                    <button class="report-print-btn"><i class="bx bx-printer"></i></button>
                </div>
                <div class="report-body">
                    <table>
                        <thead>
                            <tr>
                                <td>Product</td>
                                <td width="20%">Price</td>
                                <td>Quantity</td>
                                <td>Amount Received</td>
                            </tr>
                        </thead>
                        <tbody>';
        $total_sales = 0;
        if(mysqli_num_rows($query) > 0){
            while($row = mysqli_fetch_assoc($query)){
                $amount = $row['price'] * $row['quantity'];
                $total_sales = $total_sales + $amount;
                $output .= '<tr>
                                <td>'.$row['product_name'].'</td>
                                <td>₱ '.$row['price'].'</td>
                                <td>'.$row['quantity'].'</td>
                                <td>₱ '.$amount.'</td>
                            </tr>';
            }
            $output .= '<tr>
                <td>Generated by Shoepee Sales Management</td>
                <td></td>
                <td></td>
                <td>Total Sales Amount : ₱ '.$total_sales.'</td>
            </tr>';
            echo $output;
        } else{
            echo 'No data found';
        }
    } else{
        echo "Unable to retrieve data";
    }
?>